/** Centralized icon set — thin re-export of lucide-react under app-local names,
 * so icon choices live in one place and usage stays consistent/swappable. */
export {
  BookOpen,
  Sparkles,
  Wand2 as Wand,
  Settings,
  LayoutDashboard,
  SlidersHorizontal as Sliders,
  FileText,
  Files,
  MessageSquareQuote as MessageSquare,
  UserRound as User,
  Plus,
  Trash2 as Trash,
  X,
  Check,
  CircleCheck as CheckCircle,
  CircleAlert as AlertCircle,
  Upload,
  Download,
  Eye,
  Save,
  Pencil,
  Copy,
  ChevronRight,
  RefreshCw,
} from "lucide-react";
